"""Add grouping fields to assertions

Revision ID: 0747e09f899e
Revises: 0b2de157ec53
Create Date: 2026-09-22 18:15:04.056341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0747e09f899e'
down_revision: Union[str, Sequence[str], None] = '0b2de157ec53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    executionmode_type = sa.Enum('isolated', 'sequential', name='executionmode')
    executionmode_type.create(op.get_bind(), checkfirst=True)
    op.add_column('assertions', sa.Column('execution_mode', executionmode_type, nullable=False, server_default='isolated'))
    op.add_column('assertions', sa.Column('group_id', sa.String(length=100), nullable=True))
    op.add_column('assertions', sa.Column('sequence_order', sa.Integer(), nullable=True))
    op.add_column('assertions', sa.Column('depends_on_state', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assertions', 'depends_on_state')
    op.drop_column('assertions', 'sequence_order')
    op.drop_column('assertions', 'group_id')
    op.drop_column('assertions', 'execution_mode')
    # ### end Alembic commands ###
