"""add_invite_table

Revision ID: 0b2de157ec53
Revises: 74a49ff85e5a
Create Date: 2026-09-21 14:28:17.105123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b2de157ec53'
down_revision: Union[str, Sequence[str], None] = '74a49ff85e5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_invites',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('question_id', sa.String(), nullable=False),
    sa.Column('candidate_name', sa.String(length=300), nullable=False),
    sa.Column('candidate_email', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_candidate_invites_question_id'), 'candidate_invites', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidate_invites_question_id'), table_name='candidate_invites')
    op.drop_table('candidate_invites')
    # ### end Alembic commands ###
