"""add assertion generation jobs table

Revision ID: 20f8c82d7798
Revises: f0bf4f116a03
Create Date: 2026-09-25 12:10:00.148020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20f8c82d7798'
down_revision: Union[str, Sequence[str], None] = 'f0bf4f116a03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assertion_generation_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('question_id', sa.String(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('queued', 'analyzing', 'validating', 'completed', 'failed', 'cancelled', name='jobstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('keep_assertion_ids', sa.Text(), nullable=True),
    sa.Column('failed_assertion_ids', sa.Text(), nullable=True),
    sa.Column('target_count', sa.Integer(), nullable=False),
    sa.Column('repair_round', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assertion_generation_jobs_question_id'), 'assertion_generation_jobs', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assertion_generation_jobs_question_id'), table_name='assertion_generation_jobs')
    op.drop_table('assertion_generation_jobs')
    # ### end Alembic commands ###
