"""add assertion_set_version to submissions

Revision ID: 24278a0d11a3
Revises: 5cc0e8e1dda4
Create Date: 2026-09-30 14:34:10.329961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24278a0d11a3'
down_revision: Union[str, Sequence[str], None] = '5cc0e8e1dda4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('assertion_set_version', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'assertion_set_version')
    # ### end Alembic commands ###
