"""initial_schema_phase0

Revision ID: 437bd4622f11
Revises: 
Create Date: 2026-09-18 10:22:13.650385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '437bd4622f11'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description_html', sa.Text(), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('question_type', sa.String(length=100), nullable=False),
    sa.Column('question_bank_name', sa.String(length=300), nullable=True),
    sa.Column('reference_html', sa.Text(), nullable=True),
    sa.Column('reference_css', sa.Text(), nullable=True),
    sa.Column('reference_js', sa.Text(), nullable=True),
    sa.Column('validation_status', sa.Enum('not_run', 'passed', 'failed', name='validationstatus'), nullable=False),
    sa.Column('assertion_set_version', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assertions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('question_id', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('trigger', sa.Enum('page_load', 'click', 'change', 'input', 'hover', name='triggertype'), nullable=False),
    sa.Column('selector', sa.String(length=500), nullable=False),
    sa.Column('wait_ms', sa.Integer(), nullable=False),
    sa.Column('check_type', sa.Enum('dom_presence', 'computed_style', 'text_content', 'attribute', 'visual_region', name='checktype'), nullable=False),
    sa.Column('expected_result', sa.Text(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('is_sample', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Enum('ai_generated', 'author_added', 'ai_edited', name='assertionsource'), nullable=False),
    sa.Column('assertion_set_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assertions_question_id'), 'assertions', ['question_id'], unique=False)
    op.create_table('submissions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('question_id', sa.String(), nullable=False),
    sa.Column('candidate_name', sa.String(length=300), nullable=True),
    sa.Column('candidate_email', sa.String(length=300), nullable=True),
    sa.Column('submitted_html', sa.Text(), nullable=True),
    sa.Column('submitted_css', sa.Text(), nullable=True),
    sa.Column('submitted_js', sa.Text(), nullable=True),
    sa.Column('assertion_set_version', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'queued', 'evaluating', 'completed', 'failed', name='submissionstatus'), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.Column('max_score', sa.Integer(), nullable=True),
    sa.Column('tc_passed', sa.Integer(), nullable=True),
    sa.Column('tc_total', sa.Integer(), nullable=True),
    sa.Column('llm_passed', sa.Integer(), nullable=True),
    sa.Column('llm_total', sa.Integer(), nullable=True),
    sa.Column('ai_confidence', sa.String(length=20), nullable=True),
    sa.Column('ai_feedback_text', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissions_question_id'), 'submissions', ['question_id'], unique=False)
    op.create_table('evaluation_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('submission_id', sa.String(), nullable=False),
    sa.Column('assertion_id', sa.String(), nullable=False),
    sa.Column('assertion_set_version', sa.Integer(), nullable=False),
    sa.Column('tc_status', sa.Enum('passed', 'failed', 'not_evaluated', name='tcstatus'), nullable=False),
    sa.Column('tc_evidence_url', sa.String(length=1000), nullable=True),
    sa.Column('llm_status', sa.Enum('passed', 'failed', 'not_evaluated', name='llmstatus'), nullable=False),
    sa.Column('llm_evidence_text', sa.Text(), nullable=True),
    sa.Column('points_awarded', sa.Integer(), nullable=False),
    sa.Column('review_flag', sa.Enum('none', 'needs_review', 'overridden', name='reviewflag'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assertion_id'], ['assertions.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_results_submission_id'), 'evaluation_results', ['submission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evaluation_results_submission_id'), table_name='evaluation_results')
    op.drop_table('evaluation_results')
    op.drop_index(op.f('ix_submissions_question_id'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_assertions_question_id'), table_name='assertions')
    op.drop_table('assertions')
    op.drop_table('questions')
    # ### end Alembic commands ###
