"""add started_at to invites

Revision ID: 47c892befcd7
Revises: 15be8b2f8ce0
Create Date: 2026-09-30 12:55:48.038933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47c892befcd7'
down_revision: Union[str, Sequence[str], None] = '15be8b2f8ce0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_invites', sa.Column('started_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_invites', 'started_at')
    # ### end Alembic commands ###
