"""add starter stubs

Revision ID: 5cc0e8e1dda4
Revises: 47c892befcd7
Create Date: 2026-09-30 14:28:50.897209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cc0e8e1dda4'
down_revision: Union[str, Sequence[str], None] = '47c892befcd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('starter_html', sa.Text(), nullable=True))
    op.add_column('questions', sa.Column('starter_css', sa.Text(), nullable=True))
    op.add_column('questions', sa.Column('starter_js', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'starter_js')
    op.drop_column('questions', 'starter_css')
    op.drop_column('questions', 'starter_html')
    # ### end Alembic commands ###
