"""Add llm_status to submissions

Revision ID: 6fd29091b1aa
Revises: e7f1c2d3a4b5
Create Date: 2026-09-24 22:20:43.992935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fd29091b1aa'
down_revision: Union[str, Sequence[str], None] = 'e7f1c2d3a4b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.dialects import postgresql
    submissionllmstatus = postgresql.ENUM('evaluated', 'skipped_due_to_failure', 'skipped_passed_baseline', name='submissionllmstatus')
    submissionllmstatus.create(op.get_bind())
    op.add_column('submissions', sa.Column('llm_status', sa.Enum('evaluated', 'skipped_due_to_failure', 'skipped_passed_baseline', name='submissionllmstatus'), nullable=True))
    op.alter_column('submissions', 'tc_passed',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('submissions', 'tc_total',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('submissions', 'llm_passed',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('submissions', 'llm_total',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('submissions', 'total_score',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('submissions', 'max_score',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('submissions', 'ai_confidence',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.drop_column('submissions', 'needs_review')
    op.drop_column('submissions', 'assertion_set_version')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('assertion_set_version', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('submissions', sa.Column('needs_review', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.alter_column('submissions', 'ai_confidence',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('submissions', 'max_score',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('submissions', 'total_score',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('submissions', 'llm_total',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('submissions', 'llm_passed',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('submissions', 'tc_total',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('submissions', 'tc_passed',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('submissions', 'llm_status')
    # ### end Alembic commands ###
