"""add_missing_columns

Revision ID: 74a49ff85e5a
Revises: 437bd4622f11
Create Date: 2026-09-18 12:50:00.504434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74a49ff85e5a'
down_revision: Union[str, Sequence[str], None] = '437bd4622f11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluation_results', sa.Column('actual_result', sa.Text(), nullable=True))
    op.add_column('submissions', sa.Column('needs_review', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'needs_review')
    op.drop_column('evaluation_results', 'actual_result')
    # ### end Alembic commands ###
