"""add needs_review to submissions

Revision ID: 78fda130c991
Revises: 20f8c82d7798
Create Date: 2026-09-25 15:06:46.027423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78fda130c991'
down_revision: Union[str, Sequence[str], None] = '20f8c82d7798'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('needs_review', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'needs_review')
    # ### end Alembic commands ###
