"""Add ai_feedback_breakdown to Submission

Revision ID: b2bea8624e10
Revises: d412bdb7a37a
Create Date: 2026-09-23 12:26:05.258797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2bea8624e10'
down_revision: Union[str, Sequence[str], None] = 'd412bdb7a37a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('ai_feedback_breakdown', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'ai_feedback_breakdown')
    # ### end Alembic commands ###
