"""Split selector into trigger_selector and check_selector

Revision ID: d412bdb7a37a
Revises: 0747e09f899e
Create Date: 2026-09-22 18:29:09.817227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd412bdb7a37a'
down_revision: Union[str, Sequence[str], None] = '0747e09f899e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assertions', sa.Column('trigger_selector', sa.String(length=500), nullable=True))
    op.add_column('assertions', sa.Column('check_selector', sa.String(length=500), nullable=True))
    op.drop_column('assertions', 'selector')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assertions', sa.Column('selector', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.drop_column('assertions', 'check_selector')
    op.drop_column('assertions', 'trigger_selector')
    # ### end Alembic commands ###
