"""add assertion validation tracking

Revision ID: f0bf4f116a03
Revises: 6fd29091b1aa
Create Date: 2026-09-25 11:26:02.435016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0bf4f116a03'
down_revision: Union[str, Sequence[str], None] = '6fd29091b1aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assertions', sa.Column('last_validation_status', sa.String(length=20), nullable=False, server_default='not_run'))
    op.add_column('assertions', sa.Column('last_validation_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assertions', 'last_validation_error')
    op.drop_column('assertions', 'last_validation_status')
    # ### end Alembic commands ###
